version: "3.8"

services:

  # PHP Service
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        user: ${USER}
        uid: ${UID}
    container_name: api--app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ../:/var/www
    networks:
      - app-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: api--webserver
    restart: unless-stopped
    volumes:
      - ../:/var/www
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  db:
    platform: linux/amd64
    image: mysql:5.7.37
    container_name: api--db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
